name: Deploy Static Website 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Start server on port 3000
      run: |
        nohup python3 -m http.server 3000
