name: Deploy Static Website 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install static server
      run: npm install -g serve

    - name: Start server on port 3000
      run: |
        nohup serve -s . -l 3000 > output.log 2>&1 &
        echo "Server running at http://localhost:3000"
